{application,priyanshu_project,
             [{modules,['Elixir.FreelancerRates','Elixir.Lasagna',
                        'Elixir.PriyanshuProject','Elixir.Rules',
                        'Elixir.Secrets']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"priyanshu_project"},
              {registered,[]},
              {vsn,"0.1.0"}]}.
